// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSw9X2-mSYJvXqevYFfhp0MHXp4YV3PQ4',
    appId: '1:1085796839847:web:a4ed520746c688153cc682',
    messagingSenderId: '1085796839847',
    projectId: 'mimamu-8e378',
    authDomain: 'mimamu-8e378.firebaseapp.com',
    storageBucket: 'mimamu-8e378.appspot.com',
    measurementId: 'G-MQVDMNKG8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_kLGgqI2llYacT53TPIlA6bkbK03IlTI',
    appId: '1:1085796839847:android:b2e3dbfb0e0afa943cc682',
    messagingSenderId: '1085796839847',
    projectId: 'mimamu-8e378',
    storageBucket: 'mimamu-8e378.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClpBuURW4CwEtAyWkaceyHuhAWKeW2G1o',
    appId: '1:1085796839847:ios:ba9419b85f4309e23cc682',
    messagingSenderId: '1085796839847',
    projectId: 'mimamu-8e378',
    storageBucket: 'mimamu-8e378.appspot.com',
    iosClientId: '1085796839847-u29u5ffmlfkk4c90qo51mfav5rj80ino.apps.googleusercontent.com',
    iosBundleId: 'com.malibu.mimamu',
  );
}
